import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignIn, UserButton } from "@clerk/nextjs";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-between px-4 py-2 bg-gray-100 shadow">
            <h1 className="text-4xl font-bold">Test-Cube</h1>
            <div className="flex items-center space-x-4">
              <SignedIn>
                <Link href="/dashboard" className="text-1xl text-blue-500 hover:underline">
                  Dashboard
                </Link>
              </SignedIn>           
              <UserButton showName />            
            </div>
          </header>
          <main className="flex items-center justify-center min-h-screen bg-gray-50">
            <SignedOut>
              <div className="flex items-center justify-center w-full max-w-md p-8 bg-white shadow-md rounded-lg">
                <SignIn routing="hash" />
              </div>
            </SignedOut>
            <SignedIn>{children}</SignedIn>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
